copyright: |
  &copy; allaga.ru, 2014 - 2024

docs_dir: content

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/allaga/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/

    - icon: fontawesome/brands/python
      link: https://pypi.org/

    - icon: fontawesome/solid/globe
      link: https://allaga.ru/

    - icon: fontawesome/solid/envelope
      link: mailto:info@allaga.ru

extra_css:
  - stylesheets/extra.css

edit_uri: edit/main/content/

markdown_extensions:
  - toc:
      toc_depth: 0

plugins:
  - search:
      lang: en

remote_branch: gh-pages
remote_name: origin

repo_name: allaga/kb
repo_url: https://github.com/allaga/kb/

site_author: allaga
site_description: This is a simple knowledge base that contains information on various topics.
site_dir: public
site_name: Knowledge Base
site_url: https://kb.allaga.ru/

strict: true

use_directory_urls: false

theme:
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs

    - toc.integrate
  language: en
  name: material
