copyright: |
  &copy; 2024 <a href="https://allaga.ru/" target="_blank" rel="noopener">allaga</a>

docs_dir: content

edit_uri: edit/main/content/

plugins:
  - search:
      lang: en

remote_branch: gh-pages
remote_name: origin

repo_name: GitHub
repo_url: https://github.com/allaga/kb/

site_author: allaga
site_description: This is a simple knowledge base that contains information on various topics.
site_dir: public
site_name: Knowledge Base
site_url: https://kb.allaga.ru/

strict: true

use_directory_urls: false

theme:
  locale: en
  name: material
