# Inheritance
INHERIT: addons.yml

# The directory with the source Markdown files for the documentation.
docs_dir: ./content/

# A list of Python scripts (relative to "mkdocs.yml"), which are loaded and used as plugin instances.
hooks: ./hooks/on_post_build.py

# The directory where the HTML output and other files will be generated.
site_dir: ./public/

# Determines how warnings are handled.
strict: true

# This setting determines the style used for links to pages within your documentation.
use_directory_urls: false
