# Set a list of CSS files to be included in the theme (relative to the "docs_dir").
extra_css:
  - assets/stylesheets/extra.css

# A list of Python scripts (relative to "mkdocs.yml"), which are loaded and used as plugin instances.
hooks:
  - hooks/mv_cname.py
  - hooks/mv_robots.py
